### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Shindoku** [tonekk/ICanHaz.load#4]
Is this plugin still being maintained?
I tried to follow the README, but the following functions did not exist: ich.templatePath(), ich.template().
And ich.loadTemplate gave me an error.

ICanHaz works, but nothing in this plugin does..

**Comment by tonekk** [comment]
Did you load it **after** `ICanHaz.js` & `jQuery`?
Because it seems like you didn't.

Send me you `<head>`, I'm pretty sure the plugin works (as it's also **tested**).

**Comment by Shindoku** [comment]
JQuery, ICanHaz and this plugin are built into one file using grunt in the correct order, maybe that doesn't work?
Everything except this plugin works. I can try to load it normally.

**Comment by Shindoku** [comment]
Sorry, i got it to work, I just misunderstood how to use it. I loaded a file with multiple `<script id="name"> .. template .. </script>` and thought I could call `ich.name` like this:

tmpl.htm:
```
<script id="tmplname"> .. template .. </script>
<script id="partial"> .. template .. </script>
```
script:
```
ich.load('tmpl', function() {
  var content = ich.tmplname(data);
});
```
Would be nice if something like that worked.

Btw. templatePath is a variable, not a function, should probably fix that in the README.

**Comment by tonekk** [comment]
done :+1:
